name: Deploy Vite App to GitHub Pages

# Trigger the workflow on push to the 'main' branch
on:
    push:
        branches:
            - main # Or your target branch

# Define the job to build and deploy the Vite app
jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            id-token: write # Required for deployment
            contents: write # Allows writing to repository (needed for GitHub Pages)

        steps:
            # Step 1: Check out the repository code
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Set up Node.js to match your project version
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18" # Specify your desired Node.js version

            # Step 3: Install npm dependencies
            - name: Install dependencies
              run: npm install

            # Step 4: Build the Vite app
            - name: Build the Vite app
              run: npm run build

            # Step 5: Upload build artifact
            - name: Upload production-ready build files
              uses: actions/upload-artifact@v4
              with:
                  name: github-pages
                  path: ./dist # Folder where Vite outputs the build (default is 'dist')

    deploy:
        runs-on: ubuntu-latest
        needs: build

        permissions:
            id-token: write # Required for deployment
            contents: write # Needed to push to GitHub Pages

        steps:
            # Step 6: Download the artifact for deployment
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: github-pages

            # Step 7: Deploy to GitHub Pages
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
